[package]
name = "code-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.9"
tree-sitter-python = "0.20.2"
tree-sitter-rust = "0.20.3"
tree-sitter-go = "0.19.1"
tree-sitter-cpp = "0.20.0"
tree-sitter-c = "0.20.2"
tree-sitter-toml = "0.20.0"
